export const OppgaverTekster = {
    'oppgaver.sykepengesoknad.enkel': 'Du har en ny søknad om sykepenger',
    'oppgaver.sykepengesoknad.flere': 'Du har %ANTALL% nye søknader om sykepenger',
    'oppgaver.reisetilskudd.enkel': 'Du har en ny søknad om reisetilskudd',
    'oppgaver.reisetilskudd.flere': 'Du har %ANTALL% nye søknader om reisetilskudd',
    'oppgaver.sykmeldinger.en-sykmelding': 'Du har en ny sykmelding',
    'oppgaver.sykmeldinger.flere-sykmeldinger': 'Du har %ANTALL% nye sykmeldinger',
    'oppgaver.sykmeldinger.en-avvist-sykmelding': 'Du har en avvist sykmelding',
    'oppgaver.sykmeldinger.flere-avviste-sykmeldinger': 'Du har %ANTALL% avviste sykmeldinger',
    'oppgaver.snartslutt': 'Snart slutt på sykepengene',
    'oppgaver.snartslutt.url': '/syk/sykefravaer/snart-slutt-pa-sykepengene',
    'oppgaver.oppfoelgingsplan.avventendegodkjenninger.entall': 'Du har en oppfølgingsplan som venter på godkjenning av deg',
    'oppgaver.oppfoelgingsplan.avventendegodkjenninger.flertall': 'Du har %ANTALL% oppfølgingsplaner som venter på godkjenning av deg',
    'oppgaver.dialogmote.behov.entall': 'Du har en dialogmøte som venter på godkjenning av deg',
    'oppgaver.dialogmote.svar': 'Svar på NAVs spørsmål om dialogmøte',
    'oppgaver.oppfoelgingsplan.sykmeldt.nyeplaner.entall': 'Lederen din har begynt på oppfølgingsplanen dere skal skrive sammen',
    'oppgaver.oppfoelgingsplan.sykmeldt.nyeplaner.flertall': 'Det er startet %ANTALL% oppfølgingsplaner du er en del av',
    'oppgaver.aktivitetskrav': 'Bekreft at du kjenner aktivitetsplikten din',
}
