export const SnartsluttTekster = {
    'snartslutt.bjorntekst': 'Det begynner å nærme seg datoen du ikke lenger kan få sykepenger. ' +
        'Tror du at du snart er tilbake i jobb, eller vil du trenge noe mer fra NAV? Her kan du se hvilke muligheter du har.',
    'snartslutt.hva_nå': 'Hva kan du gjøre nå?',
    'snartslutt.andre': 'Andre muligheter',
    'snartslutt.snakk_med.tittel': 'Snakk med arbeidsgiveren din',
    'snartslutt.snakk_med.tekst': 'Arbeidsgiveren din har fortsatt ansvaret for å tilpasse arbeidsplassen og oppgavene dine slik at du kan jobbe.',
    'snartslutt.aktivitetsplan.tittel': 'Lag en aktivitetsplan',
    'snartslutt.aktivitetsplan.tekst': 'Du kan kommunisere direkte med NAV-veilederen din i en aktivitetsplan når du er logget inn på nav.no.',
    'snartslutt.planlegg.tittel': 'Planlegg økonomien din\n',
    'snartslutt.planlegg.tekst': 'Det er bare sykepenger som erstatter inntekten din med 100 prosent. Du må derfor være forberedt på å gå ned i inntekt når sykepengene tar slutt.',
    'snartslutt.bytt_jobb.tittel': 'Kan du bytte jobb?',
    'snartslutt.finn_jobb.tittel': 'Finn en jobb som passer situasjonen din',
    'snartslutt.bytt_jobb.tekst': 'Av og til er det mulig å fungere bedre i en annen jobb enn den man ble sykmeldt fra.',
    'snartslutt.bytt_jobb.liste.del1': 'På <a href="https://arbeidsplassen.nav.no/" class="lenke" target="_blank" rel="noopener noreferrer">Arbeidsplassen</a> finner du alle utlyste stillinger i landet, og sjansen er god for å finne en jobb eller bli funnet av en arbeidsgiver.',
    'snartslutt.bytt_jobb.liste.del2': 'Du kan snakke med <a href="https://www.nav.no/person/kontakt-oss/nb/" class="lenke" target="_blank" rel="noopener noreferrer">en av våre veiledere</a> om hva som kan gjøre det lettere for deg å komme i ny jobb.',
    'snartslutt.okonomien.tittel': 'Hvordan blir økonomien din?',
    'snartslutt.okonomien.tekst': 'Det er bare sykepenger som erstatter inntekten din med 100 prosent. Du må derfor være forberedt på å gå ned i inntekt når sykepengene tar slutt.',
    'snartslutt.okonomien.tekst2': 'Du kan ha rett til annen økonomisk støtte fra NAV hvis du ikke kan gå tilbake i jobb før sykepengene er slutt. Dette må du i tilfelle søke om.',
    'snartslutt.okonomien.innhold.avsnitt1': 'Du kan ha rett til annen økonomisk støtte fra NAV hvis du ikke kan gå tilbake i jobb før sykepengene er slutt. Dette må du i tilfelle søke om.',
    'snartslutt.okonomien.innhold.avsnitt2': 'Vær oppmerksom på at du ikke går automatisk over på arbeidsavklaringspenger, du må selv søke om det. Les mer på <a href="https://www.nav.no/etter-sykepenger" class="lenke" target="_blank" rel="noopener noreferrer">nav.no/etter-sykepenger</a>',
    'snartslutt.okonomien.innhold.avsnitt3': 'Undersøk også hvilke rettigheter du har hos forsikringsselskapet eller pensjonskassen du er medlem i. Det er ikke NAV som administrerer slike ordninger.',
    'snartslutt.veiledning': 'Ønsker du mer veiledning fra NAV?',
    'snartslutt.veiledning.ja': 'Ja',
    'snartslutt.veiledning.nei': 'Nei',
}
