apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-sykefravaer
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://www-gcp.dev.nav.no/syk/sykefravaer"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: SYKMELDINGER_BACKEND_PROXY_ROOT
      value: "https://sykmelding-gateway.dev.nav.no/sykmeldinger-backend"
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.dev.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.dev.nav.no/login"
    - name: MOCK_BACKEND
      value: "false"
    - name: DECORATOR_URL
      value: "https://dekoratoren.dev.nav.no"
    - name: ENVIRONMENT
      value: "q1"
    - name: DITTNAV_URL
      value: "https://www.dev.nav.no/person/dittnav/"
    - name: OPPLAERING
      value: "false"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www-gcp.dev.nav.no/syk/sykefravaer"
    - name: FRONTENDLOGGER_ROOT
      value: "https://tjenester-q1.nav.no"
    - name: AMPLITUDE_KEY
      value: "7a887ba3e5a07c755526c6591810101a"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: SYKEPENGESOKNAD_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepengesoknad"
    - name: SPINNSYN_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepenger"
    - name: SYKMELDING_URL
      value: "https://www-gcp.dev.nav.no/syk/sykmeldinger"
    - name: AKTIVITETSPLAN_URL
      value: "https://aktivitetsplan-q1.dev.nav.no/"
    - name: NARMESTELEDER_URL
      value: "https://narmesteleder.dev.nav.no"
    - name: ARBEIDSSOKERREGISTRERING_URL
      value: "https://arbeidssokerregistrering-q1.nav.no/start?fraSykefravaer=true"
    - name: SYFOAPI_ROOT
      value: "https://syfoapi.dev.nav.no"
    - name: OPPFOLGINGSPLAN_URL
      value: "https://tjenester-q1.nav.no/oppfolgingsplan/oppfolgingsplaner"
    - name: DIALOGMOTE_URL
      value: "https://tjenester-q1.nav.no/dialogmote/mote"
    - name: VEIENTILARBEID_URL
      value: "https://veientilarbeid.dev.nav.no"
