apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-sykefravaer
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://www-gcp.dev.nav.no/syk/sykefravaer"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  liveness:
      path: syk/sykefravaer/api/isAlive
  readiness:
      path: syk/sykefravaer/api/isReady
  env:
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "q1"
    - name: OPPLAERING
      value: "false"
    - name: SYKMELDINGER_BACKEND_PROXY_ROOT
      value: "https://sykmelding-gateway.dev.nav.no/sykmeldinger-backend"
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.dev.nav.no"
    - name: SYFOAPI_ROOT
      value: "https://syfoapi-sky.dev.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.dev.nav.no/login"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www-gcp.dev.nav.no/syk/sykefravaer"
    - name: SYKEPENGESOKNAD_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepengesoknad"
    - name: SPINNSYN_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepenger"
    - name: SYKMELDING_URL
      value: "https://www-gcp.dev.nav.no/syk/sykmeldinger"
    - name: AKTIVITETSPLAN_URL
      value: "https://aktivitetsplan-q1.dev.nav.no/"
    - name: OPPFOLGINGSPLAN_URL
      value: "https://www-gcp.dev.nav.no/syk/oppfolgingsplan"
    - name: DIALOGMOTE_URL
      value: "https://www-gcp.dev.nav.no/syk/dialogmote"
    - name: DITTNAV_URL
      value: "https://www.dev.nav.no/person/dittnav/"
    - name: FRONTENDLOGGER_ROOT
      value: "https://tjenester-q1.nav.no"
    - name: NARMESTELEDER_URL
      value: "https://narmesteleder.dev.nav.no"
    - name: ARBEIDSSOKERREGISTRERING_URL
      value: "https://arbeidssokerregistrering-q1.nav.no/start?fraSykefravaer=true"
    - name: DECORATOR_ENV
      value: "dev"
    - name: AMPLITUDE_KEY
      value: "7a887ba3e5a07c755526c6591810101a"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: ASSET_PREFIX
      value: "https://flex-static-files.dev.nav.no/sykefravaer"
