apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-sykefravaer
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://ditt-sykefravaer.labs.nais.io/"
    - "https://sykefravaer.labs.nais.io/"
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: LOGINSERVICE_URL
      value: "https://loginservice-q.nav.no/login"
    - name: MOCK_BACKEND
      value: "true"
    - name: ENVIRONMENT
      value: "labs"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
    - name: OPPLAERING
      value: "true"
    - name: SYKEPENGESOKNAD_URL
      value: "https://sykepengesoknad.labs.nais.io/syk/sykepengesoknad"
    - name: SPINNSYN_URL
      value: "https://sykepenger.labs.nais.io/syk/sykepenger"
    - name: SYKMELDING_URL
      value: "https://sykmeldinger.labs.nais.io/syk/sykmeldinger"
    - name: AKTIVITETSPLAN_URL
      value: "https://aktivitetsplan.nav.no/"
    - name: NARMESTELEDER_URL
      value: "https://narmesteleder.dev.nav.no"
    - name: ARBEIDSSOKERREGISTRERING_URL
      value: "https://arbeidssokerregistrering.nav.no/start?fraSykefravaer=true"
    - name: OPPFOLGINGSPLAN_URL
      value: "https://oppfolgingsplan.herokuapp.com/oppfolgingsplan/oppfolgingsplaner"
    - name: DIALOGMOTE_URL
      value: "https://dialogmote.herokuapp.com/dialogmote"
    - name: DECORATOR_ENV
      value: "dev"
