apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-sykefravaer
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://www.nav.no/syk/sykefravaer"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: SYKMELDINGER_BACKEND_PROXY_ROOT
      value: "https://sykmelding-gateway.nav.no/sykmeldinger-backend"
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.nav.no/login"
    - name: MOCK_BACKEND
      value: "false"
    - name: DECORATOR_URL
      value: "https://www.nav.no/dekoratoren"
    - name: ENVIRONMENT
      value: "prod"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
    - name: OPPLAERING
      value: "false"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www.nav.no/syk/sykefravaer"
    - name: FRONTENDLOGGER_ROOT
      value: "https://tjenester.nav.no"
    - name: AMPLITUDE_KEY
      value: "d5b43a81941b61a3b06059197807a25a"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: SYKEPENGESOKNAD_URL
      value: "https://www.nav.no/syk/sykepengesoknad"
    - name: SPINNSYN_URL
      value: "https://www.nav.no/syk/sykepenger"
    - name: SYKMELDING_URL
      value: "https://www.nav.no/syk/sykmeldinger"
    - name: AKTIVITETSPLAN_URL
      value: "https://aktivitetsplan.nav.no/"
    - name: NARMESTELEDER_URL
      value: "https://narmesteleder.nav.no"
