apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-sykefravaer
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://www-gcp.dev.nav.no/syk/sykefravaer"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  liveness:
    path: syk/sykefravaer/api/internal/isAlive
    initialDelay: 15
  readiness:
    path: syk/sykefravaer/api/internal/isReady
    initialDelay: 15
  prometheus:
    enabled: true
    path: /syk/sykefravaer/api/internal/prometheus
  accessPolicy:
    outbound:
      rules:
        - application: ditt-sykefravaer-backend
        - application: sykepengesoknad-backend
        - application: spinnsyn-backend
        - application: sykmeldinger-backend
          namespace: teamsykmelding
        - application: narmesteleder
          namespace: teamsykmelding
        - application: isdialogmote
          namespace: teamsykefravr
        - application: syfomotebehov
          namespace: team-esyfo
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "q1"
    - name: OPPLAERING
      value: "false"
    - name: SYFOAPI_ROOT
      value: "https://syfoapi-sky.dev.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.dev.nav.no/login"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www-gcp.dev.nav.no/syk/sykefravaer"
    - name: SYKEPENGESOKNAD_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepengesoknad"
    - name: SPINNSYN_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepenger"
    - name: SYKMELDING_URL
      value: "https://www-gcp.dev.nav.no/syk/sykmeldinger"
    - name: AKTIVITETSPLAN_URL
      value: "https://aktivitetsplan-q1.dev.nav.no/"
    - name: OPPFOLGINGSPLAN_URL
      value: "https://www-gcp.dev.nav.no/syk/oppfolgingsplan"
    - name: DIALOGMOTE_URL
      value: "https://www-gcp.dev.nav.no/syk/dialogmoter/sykmeldt"
    - name: MINSIDE_URL
      value: "https://www.dev.nav.no/minside/"
    - name: DECORATOR_ENV
      value: "dev"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: ASSET_PREFIX
      value: "https://flex-static-files.dev.nav.no/sykefravaer"
    - name: SNART_SLUTT_URL
      value: "https://www-gcp.dev.nav.no/syk/info/snart-slutt-pa-sykepengene"
    - name: DITT_SYKEFRAVAER_BACKEND_CLIENT_ID
      value: "dev-gcp:flex:ditt-sykefravaer-backend"
    - name: SPINNSYN_BACKEND_CLIENT_ID
      value: "dev-gcp:flex:spinnsyn-backend"
    - name: SYKMELDINGER_BACKEND_CLIENT_ID
      value: "dev-gcp:teamsykmelding:sykmeldinger-backend"
    - name: NARMESTELEDER_CLIENT_ID
      value: "dev-gcp:teamsykmelding:narmesteleder"
    - name: SYKEPENGESOKNAD_BACKEND_CLIENT_ID
      value: "dev-gcp:flex:sykepengesoknad-backend"
    - name: ISDIALOGMOTE_CLIENT_ID
      value: "dev-gcp:teamsykefravr:isdialogmote"
    - name: SYFOMOTEBEHOV_CLIENT_ID
      value: "dev-fss:team-esyfo:syfomotebehov"
    - name: SYFOMOTEBEHOV_URL
      value: "https://syfomotebehov.dev-fss-pub.nais.io"
    - name: VEILARBOPPFOLGING_HOST
      value: "veilarboppfolging.dev-fss-pub.nais.io"
    - name: VEILARBOPPFOLGING_CLIENT_ID
      value: "dev-fss:pto:veilarboppfolging"
