apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-sykefravaer
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://www.nav.no/syk/sykefravaer"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  liveness:
      path: syk/sykefravaer/api/isAlive
  readiness:
      path: syk/sykefravaer/api/isReady
  env:
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "prod"
    - name: OPPLAERING
      value: "false"
    - name: SYKMELDINGER_BACKEND_PROXY_ROOT
      value: "https://sykmelding-gateway.nav.no/sykmeldinger-backend"
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.nav.no"
    - name: SYFOAPI_ROOT
      value: "https://syfoapi.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.nav.no/login"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www.nav.no/syk/sykefravaer"
    - name: SYKEPENGESOKNAD_URL
      value: "https://www.nav.no/syk/sykepengesoknad"
    - name: SPINNSYN_URL
      value: "https://www.nav.no/syk/sykepenger"
    - name: SYKMELDING_URL
      value: "https://www.nav.no/syk/sykmeldinger"
    - name: AKTIVITETSPLAN_URL
      value: "https://aktivitetsplan.nav.no/"
    - name: OPPFOLGINGSPLAN_URL
      value: "https://www.nav.no/syk/oppfolgingsplan"
    - name: DIALOGMOTE_URL
      value: "https://www.nav.no/syk/dialogmote"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
    - name: FRONTENDLOGGER_ROOT
      value: "https://tjenester.nav.no"
    - name: NARMESTELEDER_URL
      value: "https://narmesteleder.nav.no"
    - name: ARBEIDSSOKERREGISTRERING_URL
      value: "https://arbeidssokerregistrering.nav.no/start?fraSykefravaer=true"
    - name: DECORATOR_ENV
      value: "prod"
    - name: AMPLITUDE_KEY
      value: "d5b43a81941b61a3b06059197807a25a"
    - name: AMPLITUDE_ENABLED
      value: "true"
