apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ appname }}
  namespace: flex
  labels:
    team: flex
    branchState: {{ branchState }}
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - {{ ingress }}
  replicas:
    min: {{ replicas }}
    max: {{ replicas }}
  liveness:
    path: syk/sykefravaer/api/internal/isAlive
  readiness:
    path: syk/sykefravaer/api/internal/isReady
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  {{#if TTL_HOURS}}
  ttl: {{ TTL_HOURS }}
  {{/if }}
  env:
    - name: ENVIRONMENT
      value: "labs"
    - name: DECORATOR_ENV
      value: "prod"
