replicas_min: 1
replicas_max: 2
ingress: https://www.ekstern.dev.nav.no/syk/sykefravaer
cpu_limits: 1000m
cpu_requests: 100m
sidecar_cpu: 200m
memory_limits: 300Mi
memory_requests: 200Mi
sidecar_memory_limits: 256Mi
sidecar_memory_requests: 32Mi
external-host:
  - syfooppfolgingsplanservice.dev-fss-pub.nais.io
  - veilarboppfolging.dev-fss-pub.nais.io
  - syfomotebehov.dev-fss-pub.nais.io
env:
  MOCK_BACKEND: false
  ENVIRONMENT: q1
  OPPLAERING: false
  SYKEPENGESOKNAD_URL: https://www.ekstern.dev.nav.no/syk/sykepengesoknad
  SPINNSYN_URL: https://www.ekstern.dev.nav.no/syk/sykepenger
  SYKMELDING_URL: https://www.ekstern.dev.nav.no/syk/sykmeldinger
  AKTIVITETSPLAN_URL: https://aktivitetsplan-q1.dev.nav.no/
  OPPFOLGINGSPLAN_URL: https://www-gcp.dev.nav.no/syk/oppfolgingsplaner/sykmeldt
  DIALOGMOTE_URL: https://www-gcp.dev.nav.no/syk/dialogmoter/sykmeldt
  MINSIDE_URL: https://www.dev.nav.no/minside/
  DECORATOR_ENV: dev
  AMPLITUDE_ENABLED: true
  ASSET_PREFIX: https://cdn.nav.no/flex/ditt-sykefravaer
  DITT_SYKEFRAVAER_BACKEND_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer-backend
  SPINNSYN_BACKEND_CLIENT_ID: dev-gcp:flex:spinnsyn-backend
  SYKMELDINGER_BACKEND_CLIENT_ID: dev-gcp:teamsykmelding:sykmeldinger-backend
  NARMESTELEDER_CLIENT_ID: dev-gcp:teamsykmelding:narmesteleder
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: dev-gcp:flex:sykepengesoknad-backend
  ISDIALOGMOTE_CLIENT_ID: dev-gcp:teamsykefravr:isdialogmote
  SYFOMOTEBEHOV_CLIENT_ID: dev-fss:team-esyfo:syfomotebehov
  SYFOMOTEBEHOV_URL: https://syfomotebehov.dev-fss-pub.nais.io
  SYFOMOTEBEHOV_HOST: syfomotebehov.dev-fss-pub.nais.io
  VEILARBOPPFOLGING_HOST: veilarboppfolging.dev-fss-pub.nais.io
  VEILARBOPPFOLGING_CLIENT_ID: dev-fss:pto:veilarboppfolging
  SYFOOPPFOLGINGSPLANSERVICE_HOST: syfooppfolgingsplanservice.dev-fss-pub.nais.io
  SYFOOPPFOLGINGSPLANSERVICE_CLIENT_ID: dev-fss:team-esyfo:syfooppfolgingsplanservice
