replicas_min: 1
replicas_max: 2
ingresses:
  - https://www.ekstern.dev.nav.no/syk/sykefravaer
  - https://www.ekstern.dev.nav.no/syk/sykmeldinger
cpu: 200m
memory: 384Mi
sidecar_cpu: 200m
sidecar_memory: 128Mi
external-host:
  - syfooppfolgingsplanservice.dev-fss-pub.nais.io
  - veilarboppfolging.intern.dev.nav.no
  - flex-unleash-api.nav.cloud.nais.io
env:
  MOCK_BACKEND: false
  ENVIRONMENT: q1
  OPPLAERING: false
  SYKEPENGESOKNAD_URL: https://www.ekstern.dev.nav.no/syk/sykepengesoknad
  SPINNSYN_URL: https://www.ekstern.dev.nav.no/syk/sykepenger
  AKTIVITETSPLAN_URL: https://aktivitetsplan.ekstern.dev.nav.no/
  OPPFOLGINGSPLAN_URL: https://www.ekstern.dev.nav.no/syk/oppfolgingsplaner/sykmeldt
  DIALOGMOTE_URL: https://www.ekstern.dev.nav.no/syk/dialogmoter/sykmeldt
  MINSIDE_URL: https://www.intern.dev.nav.no/minside/
  DECORATOR_ENV: dev
  AMPLITUDE_ENABLED: true
  ASSET_PREFIX: https://cdn.nav.no/flex/ditt-sykefravaer
  DITT_SYKEFRAVAER_BACKEND_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer-backend
  SPINNSYN_BACKEND_CLIENT_ID: dev-gcp:flex:spinnsyn-backend
  FLEX_SYKMELDINGER_BACKEND_CLIENT_ID: dev-gcp:flex:flex-sykmeldinger-backend
  NARMESTELEDER_CLIENT_ID: dev-gcp:teamsykmelding:narmesteleder
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: dev-gcp:flex:sykepengesoknad-backend
  SYFOMOTEBEHOV_CLIENT_ID: dev-gcp:team-esyfo:syfomotebehov
  VEILARBOPPFOLGING_HOST: veilarboppfolging.intern.dev.nav.no
  VEILARBOPPFOLGING_CLIENT_ID: dev-gcp:poao:veilarboppfolging
  SYFOOPPFOLGINGSPLANSERVICE_HOST: syfooppfolgingsplanservice.dev-fss-pub.nais.io
  SYFOOPPFOLGINGSPLANSERVICE_CLIENT_ID: dev-fss:team-esyfo:syfooppfolgingsplanservice
  FLEXJAR_BACKEND_CLIENT_ID: dev-gcp:flex:flexjar-backend
  SYKEPENGEDAGER_INFORMASJON_CLIENT_ID: dev-gcp:team-esyfo:sykepengedager-informasjon
