apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-sykefravaer
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 50
  preStopHook:
    http:
      path: syk/sykefravaer/api/internal/preStop
      port: 8080
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      resources:
        limits:
          memory: {{sidecar_memory}}
        requests:
          cpu: {{sidecar_cpu}}
          memory: {{sidecar_memory}}
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  liveness:
    path: syk/sykefravaer/api/internal/isAlive
  readiness:
    path: syk/sykefravaer/api/internal/isReady
  startup:
    path: syk/sykefravaer/api/internal/isAlive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /syk/sykefravaer/api/internal/prometheus
  frontend:
    generatedConfig:
      mountPath: /usr/share/nginx/html/js/nais.js
  accessPolicy:
    outbound:
      rules:
        - application: ditt-sykefravaer-backend
        - application: sykepengesoknad-backend
        - application: spinnsyn-backend
        - application: flexjar-backend
        - application: sykmeldinger-backend
          namespace: teamsykmelding
        - application: narmesteleder
          namespace: teamsykmelding
        - application: syfomotebehov
          namespace: team-esyfo
        - application: nav-dekoratoren
          namespace: personbruker
        - application: esyfovarsel
          namespace: team-esyfo
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
  envFrom:
    - secret: ditt-sykefravaer-frontend-unleash-api-token
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
