replicas_min: 2
replicas_max: 6
ingresses:
  - https://www.nav.no/syk/sykefravaer
cpu: 200m
memory: 700Mi
sidecar_cpu: 700m
sidecar_memory: 256Mi
external-host:
  - syfooppfolgingsplanservice.prod-fss-pub.nais.io
  - veilarboppfolging-gcp.intern.nav.no
  - flex-unleash-api.nav.cloud.nais.io
env:
  MOCK_BACKEND: false
  ENVIRONMENT: prod
  OPPLAERING: false
  SYKEPENGESOKNAD_URL: https://www.nav.no/syk/sykepengesoknad
  SPINNSYN_URL: https://www.nav.no/syk/sykepenger
  AKTIVITETSPLAN_URL: https://aktivitetsplan.nav.no/
  OPPFOLGINGSPLAN_URL: https://www.nav.no/syk/oppfolgingsplaner/sykmeldt
  DIALOGMOTE_URL: https://www.nav.no/syk/dialogmoter/sykmeldt
  MINSIDE_URL: https://www.nav.no/minside
  DECORATOR_ENV: prod
  AMPLITUDE_ENABLED: true
  ASSET_PREFIX: https://cdn.nav.no/flex/ditt-sykefravaer
  DITT_SYKEFRAVAER_BACKEND_CLIENT_ID: prod-gcp:flex:ditt-sykefravaer-backend
  SPINNSYN_BACKEND_CLIENT_ID: prod-gcp:flex:spinnsyn-backend
  FLEX_SYKMELDINGER_BACKEND_CLIENT_ID: prod-gcp:flex:flex-sykmeldinger-backend
  NARMESTELEDER_CLIENT_ID: prod-gcp:teamsykmelding:narmesteleder
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: prod-gcp:flex:sykepengesoknad-backend
  SYFOMOTEBEHOV_CLIENT_ID: prod-gcp:team-esyfo:syfomotebehov
  VEILARBOPPFOLGING_HOST: veilarboppfolging-gcp.intern.nav.no
  VEILARBOPPFOLGING_CLIENT_ID: prod-gcp:poao:veilarboppfolging
  SYFOOPPFOLGINGSPLANSERVICE_HOST: syfooppfolgingsplanservice.prod-fss-pub.nais.io
  SYFOOPPFOLGINGSPLANSERVICE_CLIENT_ID: prod-fss:team-esyfo:syfooppfolgingsplanservice
  FLEXJAR_BACKEND_CLIENT_ID: prod-gcp:flex:flexjar-backend
  SYKEPENGEDAGER_INFORMASJON_CLIENT_ID: prod-gcp:team-esyfo:sykepengedager-informasjon
