replicas_min: 2
replicas_max: 6
ingresses:
  - https://www.nav.no/syk/sykefravaer
  - https://www.nav.no/syk/sykmeldinger
cpu: 200m
memory: 700Mi
sidecar_cpu: 700m
sidecar_memory: 256Mi
external-host:
  - veilarboppfolging-gcp.intern.nav.no
  - flex-unleash-api.nav.cloud.nais.io
env:
  ENVIRONMENT: prod
  DECORATOR_ENV: prod
  DITT_SYKEFRAVAER_BACKEND_CLIENT_ID: prod-gcp:flex:ditt-sykefravaer-backend
  SPINNSYN_BACKEND_CLIENT_ID: prod-gcp:flex:spinnsyn-backend
  FLEX_SYKMELDINGER_BACKEND_CLIENT_ID: prod-gcp:flex:flex-sykmeldinger-backend
  NARMESTELEDER_CLIENT_ID: prod-gcp:teamsykmelding:narmesteleder
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: prod-gcp:flex:sykepengesoknad-backend
  SYFOMOTEBEHOV_CLIENT_ID: prod-gcp:team-esyfo:syfomotebehov
  VEILARBOPPFOLGING_HOST: veilarboppfolging-gcp.intern.nav.no
  VEILARBOPPFOLGING_CLIENT_ID: prod-gcp:poao:veilarboppfolging
  FLEXJAR_BACKEND_CLIENT_ID: prod-gcp:flex:flexjar-backend
  SYKEPENGEDAGER_INFORMASJON_CLIENT_ID: prod-gcp:team-esyfo:sykepengedager-informasjon
