export const TidslinjenTekster = {
    'tidslinje.introtekst': 'På tidslinjen ser du hva som forventes av deg i løpet av sykefraværet. Oppgavene kan gjøres på andre tidspunkter hvis det er behov for det. Hvis du er for syk til å delta i jobb eller aktivitet, kan du få unntak fra enkelte av oppgavene\n',
    'tidslinje.antall-uker.4': '4 uker',
    'tidslinje.antall-uker.7': '7 uker',
    'tidslinje.antall-uker.8': '8 uker',
    'tidslinje.antall-uker.12': '12 uker',
    'tidslinje.antall-uker.17': '17 uker',
    'tidslinje.antall-uker.26': '26 uker',
    'tidslinje.antall-uker.39': '39 uker',
    'tidslinje.forste-sykmeldingsdag': 'Første sykmeldingsdag %DATO%',
    'tidslinje.sykefravaeret-starter': 'Sykefraværet starter',

    'tidslinje.aktivitetskrav-varsel.MED_ARBEIDSGIVER.budskap': '<h4>Aktivitetsplikt</h4><p>Som sykmeldt har du en plikt til å være i aktivitet hvis det er mulig. Aktivitet vil si å jobbe noe, i kombinasjon med å være sykmeldt. Et eksempel er å jobbe 50 prosent og være 50 prosent sykmeldt. Er det noen arbeidsoppgaver du kan delta i selv om du er syk?</p><h4>Hva må du gjøre nå?</h4><p>Det er viktig at du har god dialog med arbeidsgiveren din om hva som skal til for at du kan være noe i arbeid. Hvis dere ikke har hatt dialog, ta kontakt og be om en samtale.</p><h4>Hva skjer hvis aktivitet ikke er mulig?</h4><p>Hvis det ikke er mulig å legge til rette for aktivitet på arbeidsplassen, må arbeidsgiveren din gi skriftlig beskjed til NAV. Hvis du er for syk til å være i aktivitet, må den som har sykmeldt deg begrunne dette i sykmeldingen til NAV.</p><h4>NAV vurderer aktivitetsplikten</h4><p>NAV har som oppgave å vurdere aktivitetsplikten basert på opplysninger fra din lege/sykmelder og arbeidsgiver. Utfallet av vurderingen kan være:<ol type="A"><li>Aktivitetsplikten er oppfylt fordi du er delvis tilbake i arbeid. Utbetalingen av sykepenger fortsetter.</li><li>Du får unntak fra aktivitetsplikten på grunn av helsesituasjonen, eller fordi det ikke er mulig å tilrettelegge på arbeidsplassen. Utbetalingen av sykepenger fortsetter.</li><li>Aktivitetsplikten er ikke oppfylt. Du kan miste retten til sykepenger, og utbetalingen stanses.</li></ol>',
    'tidslinje.aktivitetskrav-varsel.MED_ARBEIDSGIVER.tittel': '<h3>%DATO%</h3><p>NAV skal vurdere din aktivitetsplikt om to uker, og <strong>om du fortsatt har rett til sykepenger.</strong></p>',
    'tidslinje.aktivitetskrav-varsel.UTEN_ARBEIDSGIVER.budskap': '<h4>Aktivitetsplikt</h4><p>Som sykmeldt har du en plikt til å være i aktivitet hvis det er mulig. Aktivitet vil si å jobbe noe, i kombinasjon med å være sykmeldt. Et eksempel er å jobbe 50 prosent og være 50 prosent sykmeldt. Er det noen arbeidsoppgaver du kan utføre selv om du er syk?</p><h4>Hva må du gjøre nå?</h4><p>Det er viktig at du har god dialog med den som har sykmeldt deg, om hva som skal til for at du kan være noe i arbeid. Det er NAV-kontoret som skal følge deg opp. Ta kontakt med NAV-kontoret der du bor for en samtale om mulighet til å være i aktivitet.</p><h4>Hva skjer hvis aktivitet ikke er mulig?</h4><p>Hvis du er for syk til å være i aktivitet, må den som har sykmeldt deg begrunne dette i sykmeldingen til NAV.</p><h4>NAV vurderer aktivitetsplikten</h4><p>NAV har som oppgave å vurdere aktivitetsplikten basert på opplysninger fra din lege/sykmelder. Utfallet av vurderingen kan være:</p><ol type="A"><li>Aktivitetsplikten er oppfylt fordi du er delvis tilbake i arbeid. Utbetalingen av sykepenger fortsetter.</li><li>Du får unntak fra aktivitetsplikten på grunn av helsesituasjonen. Utbetalingen av sykepenger fortsetter.</li><li>Aktivitetsplikten er ikke oppfylt. Du kan miste retten til sykepenger, og utbetalingen stanses.</li></ol>',
    'tidslinje.aktivitetskrav-varsel.UTEN_ARBEIDSGIVER.tittel': '<h3>%DATO%</h3><p>NAV skal vurdere din aktivitetsplikt om to uker, og <strong>om du fortsatt har rett til sykepenger.</strong></p>',

    'tidslinje.aktivitetskrav.MED_ARBEIDSGIVER.budskap': '<p>Du har plikt til å være i aktivitet mens du er sykmeldt – hvis det er mulig. Hensikten er å unngå at sykefraværet blir unødvendig langt. Ved alvorlig sykdom er det naturligvis unntak.</p>\n<p>Når du har vært sykmeldt i åtte uker, er det NAVs oppgave å vurdere om du oppfyller aktivitetsplikten, eller om sykepengene dine skal stanses.</p>\n<p>Når vi vurderer om du oppfyller aktivitetsplikten, ser vi på hva arbeidsgiveren din har gjort for at du kan jobbe. Vi vurderer også om du er for syk til å være i aktivitet.</p>\n<p>Er du allerede delvis tilbake i arbeid, oppfyller du aktivitetsplikten og kan fortsatt få sykepenger.</p>\n<p>Les mer om <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykepenger/hva-er-aktivitetsplikten">aktivitetsplikten</a> eller se filmen <a href="https://video.qbrick.com/play2/embed/player?accountId=763558&mediaId=7731f50f-00015227-3808f149&configId=default&pageStyling=adaptive&autoplay=false&repeat=true&sharing=true&download=true">Hva innebærer aktivitetsplikten</a></p>',
    'tidslinje.aktivitetskrav.MED_ARBEIDSGIVER.tittel': 'Oppfyller du aktivitetsplikten?',
    'tidslinje.aktivitetsplan.UTEN_ARBEIDSGIVER.budskap': '<p>Hvis du ikke allerede har vært på NAV-kontoret og laget en aktivitetsplan, kan du logge deg inn på nav.no og ta i bruk den digitale aktivitetsplanen. Legg inn aktiviteter som du mener er nyttige for å komme i jobb. Du kan starte en dialog med veilederen når du er inne i planen. Veilederen kan også starte en dialog med deg.</p>\n<p>Planen vil avhenge av hvilken aktivitet som er mulig ut fra helsesituasjonen din.</p>\n<p>Les mer om <a href="https://www.nav.no/no/person/arbeid/oppfolging-og-tiltak-for-a-komme-i-jobb/relatert-informasjon/din-aktivitetsplan">aktivitetsplanen</a>.</p>',
    'tidslinje.aktivitetsplan.UTEN_ARBEIDSGIVER.tittel': 'Har du og veilederen laget en plan?',

    'tidslinje.dialogmote-arbeidsgiver.MED_ARBEIDSGIVER.budskap': '<p>Nå er tiden kommet for å diskutere situasjonen nærmere med lederen din. Hvilke muligheter ser dere framover?</p><p>Arbeidsgiveren har ansvar for at dere møtes til en samtale før det har gått 7 uker. Unntaket er naturligvis hvis du er alvorlig syk eller du er i en annen situasjon som gjør det vanskelig.</p>\n<p>Les mer om <a href="https://www.nav.no/no/bedrift/oppfolging/sykmeldt-arbeidstaker/relatert-informasjon/slik-folger-du-opp-sykmeldte/dialogmote-1-arbeidsgiver_kap">dialogmøte på arbeidsplassen</a></p>',
    'tidslinje.dialogmote-arbeidsgiver.MED_ARBEIDSGIVER.tittel': 'Tid for dialogmøte med lederen din',
    'tidslinje.dialogmote-nav.MED_ARBEIDSGIVER.budskap': '<p>Det kan hende du snart blir innkalt til dialogmøte med NAV – hvis du ikke allerede har vært der? I dette møtet kommer du sammen med arbeidsgiveren, av og til blir også den som har sykmeldt deg invitert.</p>\n<p>Meningen er å komme fram til noe som kan hjelpe deg videre. Veilederen fra NAV leder møtet og er en nøytral deltaker som stiller spørsmål til alle som er til stede.</p>\n<p>Du forteller om jobben og situasjonen din: hva som går bra og hva som er vanskelig. Arbeidsgiveren din forteller om arbeidsplassen, hva som er forsøkt og hvilke muligheter som finnes.</p>\n<p>Vi ser på oppfølgingsplanen som du og arbeidsgiveren allerede har laget sammen. Ser vi noen flere muligheter på arbeidsplassen? Trenger du noen helsetjenester, eller er det noe NAV kan bidra med?</p>\n<p>Til slutt oppsummerer NAV-veilederen møtet og avklarer hvem som skal gjøre hva og når det skal skje.</p>\n<p>Les mer om <a href="https://www.nav.no/no/bedrift/oppfolging/sykmeldt-arbeidstaker/relatert-informasjon/slik-folger-du-opp-sykmeldte/dialogmote-2-og-3-nav_kap">dialogmøte i regi av NAV</a> eller se filmen <a href="http://video.qbrick.com/play2/embed/player?accountId=763558&mediaId=0915c6b6-00015227-23a22cb3&configId=default&pageStyling=adaptive&autoplay=true&repeat=true&sharing=true">Hva skjer i dialogmøtet som NAV innkaller til?</a></p>',
    'tidslinje.dialogmote-nav.MED_ARBEIDSGIVER.tittel': 'Tid for dialogmøte med NAV',

    'tidslinje.mulighet-for-aktivitet.UTEN_ARBEIDSGIVER.budskap': '<p>Du har vært sykmeldt en stund, og avhengig av helsesituasjonen er det tid for å vurdere veien videre:</p>\n<ul><li>Er det noen arbeidsoppgaver jeg kan gjøre selv om jeg er syk?</li><li>Er det noe jeg trenger for å kunne komme tilbake i jobb?</li></ul>\n<p>Ta gjerne kontakt med NAV-kontoret hvis du vil drøfte hvilke muligheter du har.</p>\n<p>Etter åtte uker skal NAV vurdere om du fortsatt har rett til sykepenger. Reglene sier at du har plikt til å være i aktivitet hvis det er mulig. Hensikten er å unngå at sykefraværet blir unødvendig langt. Ved alvorlig sykdom er det naturligvis unntak.</p>\n<p>Les mer om <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykepenger/hva-er-aktivitetsplikten">aktivitetsplikten</a> eller se filmen <a href="https://video.qbrick.com/play2/embed/player?accountId=763558&mediaId=7731f50f-00015227-3808f149&configId=default&pageStyling=adaptive&autoplay=false&repeat=true&sharing=true&download=true">Hva innebærer aktivitetsplikten?</a></p>',
    'tidslinje.mulighet-for-aktivitet.UTEN_ARBEIDSGIVER.tittel': 'Har du vurdert din mulighet for å være i aktivitet?',

    'tidslinje.ny-naermeste-leder.MED_ARBEIDSGIVER.budskap': '<h4>Hvorfor trenger NAV å vite hvem som er din nærmeste leder?</h4>\n<p>Vi trenger å vite hvem vi kan kontakte hvis det er\n    behov for samarbeid med arbeidsgiveren din, slik at du kan følges opp på best mulig måte. Lederen vil få se\n    sykmeldinger du sender inn dersom du bekrefter at navnet fortsatt stemmer.</p>\n<p>Koblingen mellom deg og %NAVN% er %STATUS%</p>',
    'tidslinje.ny-naermeste-leder.MED_ARBEIDSGIVER.tittel': '<h3>%DATO%</h3><p>%ARBEIDSGIVER% har oppgitt <strong>%NAERMESTELEDER%</strong> som din nærmeste leder med personalansvar.</p>',
    'tidslinje.ny-naermeste-leder.UTEN_ARBEIDSGIVER.budskap': '<h4>Er personalleder som er oppgitt feil?</h4>\n<p>Dersom personalansvarlig er feil må du <a href="#">melde fra om det</a></p><h4>Hvorfor trenger NAV å vite hvem som er din personalleder?</h4><p>Personallederen din vil få tilgang til sykmeldingen din på nav.no, og få tilpasset informasjon fra NAV i forbindelse med sykefraværet, slik at du kan følges opp på best mulig måte.</p>\n<p>Koblingen mellom deg og %NAVN% er %STATUS%</p>',
    'tidslinje.ny-naermeste-leder.UTEN_ARBEIDSGIVER.tittel': '<h3>%DATO%</h3><p>%ARBEIDSGIVER% har oppgitt <strong>%NAERMESTELEDER%</strong> som din personalansvarlige leder</p>',

    'tidslinje.sluttfasen.MED_ARBEIDSGIVER.budskap': '<p>Blir du sykmeldt lenger enn 52 uker til sammen, har du ikke lenger rett til sykepenger. Du har ulike alternativer for å unngå å stå uten inntekt når sykepengene tar slutt. Sammen med arbeidsgiveren din eller en NAV-veileder kan du planlegge veien videre. Du kan når som helst be om et nytt dialogmøte eller en individuell samtale med en veileder på NAV-kontoret.</p>',
    'tidslinje.sluttfasen.MED_ARBEIDSGIVER.tittel': 'Snart slutt på sykepengene',
    'tidslinje.sluttfasen.UTEN_ARBEIDSGIVER.budskap': '<p>Blir du sykmeldt lenger enn 52 uker til sammen, har du ikke lenger rett til sykepenger. Du har ulike alternativer for å unngå å stå uten inntekt når sykepengene tar slutt. Sammen med en NAV-veileder kan du planlegge veien videre. Du kan når som helst be om et nytt dialogmøte eller en individuell samtale med en veileder på NAV-kontoret.</p>',
    'tidslinje.sluttfasen.UTEN_ARBEIDSGIVER.tittel': 'Snart slutt på sykepengene',

    'tidslinje.snakk-med-arbeidsgiver.MED_ARBEIDSGIVER.budskap': '<p>Du har vært sykmeldt en stund, og nå er det tid for at du og lederen din fyller ut oppfølgingsplanen sammen – med mindre det er åpenbare grunner til å la være.</p>\n<p>Oppfølgingsplanen skal gjøre det lettere å tenke gjennom:</p>\n<ul><li>Er det noen arbeidsoppgaver jeg kan gjøre selv om jeg er syk?</li>\n  <li>Er det noe som kan gjøres for at jeg kan få det til?</li></ul>\n<p>Les mer om <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmeldt/hva-er-en-oppfolgingsplan">oppfølgingsplanen</a> eller se filmen <a href="http://video.qbrick.com/play2/embed/player?accountId=763558&mediaId=25edfd35-00015227-b68553ad&configId=default&pageStyling=adaptive&autoplay=true&repeat=true&sharing=true">om den digitale oppfølgingsplanen</a>.</p>\n<p>Husk at du alltid kan vurdere <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmelding-ulike-former/gradertsykemelding">gradert sykmelding</a>.</p>',
    'tidslinje.snakk-med-arbeidsgiver.MED_ARBEIDSGIVER.tittel': 'Snakk med arbeidsgiveren din',
    'tidslinje.snakk-med-nav.UTEN_ARBEIDSGIVER.budskap': '<p>NAV skal hjelpe deg med å vurdere mulighetene dine og vil eventuelt innkalle deg til samtale. Meningen er å komme fram til noe som kan hjelpe deg videre.</p>\n<p>Husk at du kan registrere CV-en din på nav.no, hvor du også finner alle offentlig utlyste stillinger. Opplysningene du legger inn kan brukes i dialogen med NAV.</p>\n<p>På nav.no kan du lage din egen aktivitetsplan. Legg inn aktiviteter som du mener er nyttige for å komme i jobb. Du kan starte en dialog med veilederen når du er inne i planen. Veilederen kan også starte en dialog med deg.</p><p>Les mer om <a href="https://www.nav.no/no/person/arbeid/oppfolging-og-tiltak-for-a-komme-i-jobb/relatert-informasjon/din-aktivitetsplan">aktivitetsplanen</a>.<p>',
    'tidslinje.snakk-med-nav.UTEN_ARBEIDSGIVER.tittel': 'Har du snakket med en veileder på NAV-kontoret?',

    'tidslinje.sykmeldt-hva-naa.MED_ARBEIDSGIVER.budskap': '<p>Du bestemmer selv om du vil bruke sykmeldingen eller avbryte den. Du kan også jobbe i kombinasjon med sykmelding. Det kommer an på hva sykdommen din tillater og hva det er praktisk mulig å få til på arbeidsplassen.</p>\n<p>Greit å vite: Arbeidsgiveren har plikt til å legge til rette for at du kan jobbe helt eller delvis selv om du er syk.</p>\n<p>Husk at du alltid kan vurdere <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmelding-ulike-former/gradertsykemelding">gradert sykmelding</a>.</p>\n<p>Vet du at fraværet blir kort, kan det være like greit med <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmelding-ulike-former/egenmelding">egenmelding</a>, så slipper du å gå til legen.</p>\n<p>Les mer om <a href="https://www.nav.no/no/Person/Arbeid/Sykmeldt%2C+arbeidsavklaringspenger+og+yrkesskade/Sykmeldt">sykmelding og sykepenger</a> eller se filmen <a href="https://video.qbrick.com/play2/embed/player?accountId=763558&mediaId=B248D6CB&configId=default&pageStyling=adaptive&autoplay=false&repeat=false&sharing=false&download=true">Hva skjer etter at jeg har sendt sykmeldingen?</a></p>',
    'tidslinje.sykmeldt-hva-naa.MED_ARBEIDSGIVER.tittel': 'Når du er blitt syk',
    'tidslinje.sykmeldt-hva-naa.UTEN_ARBEIDSGIVER.budskap': '<p>Du bestemmer selv om du vil bruke sykmeldingen. Du kan enten bekrefte den eller avbryte den.</p>\n<p>I noen tilfeller kan det være godt å få jobbe selv om du er syk. Det kommer an på hva sykdommen din tillater og hva som er praktisk mulig å få til.</p>\n<p>Ta gjerne kontakt med NAV-kontoret hvis du vil drøfte hvilke muligheter du har.</p>\n<p>Husk at du alltid kan vurdere <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmelding-ulike-former/gradertsykemelding">gradert sykmelding</a>.</p>\n<p><a href="https://www.nav.no/no/Person/Arbeid/Sykmeldt%2C+arbeidsavklaringspenger+og+yrkesskade/Sykmeldt">Les mer om sykmelding og sykepenger</a></p>',
    'tidslinje.sykmeldt-hva-naa.UTEN_ARBEIDSGIVER.tittel': 'Når du er blitt syk',

    'tidslinje.langtidssykmeldt.MED_ARBEIDSGIVER.budskap': '<p>Du har kanskje vært i dialogmøte med NAV? Da handler det om å følge opp det som ble avtalt i møtet. Planene avhenger av hva som er mulig ut fra helsesituasjonen din.</p>\n<p>Arbeidsgiveren din har fortsatt et ansvar. Du kan be NAV om et <a href="https://www.nav.no/no/bedrift/oppfolging/sykmeldt-arbeidstaker/relatert-informasjon/slik-folger-du-opp-sykmeldte/dialogmote-2-og-3-nav_kap">nytt dialogmøte</a> sammen med lederen din og eventuelt legen.</p>',
    'tidslinje.langtidssykmeldt.MED_ARBEIDSGIVER.tittel': 'Når du har vært sykmeldt lenge',
}
