import './run-0/forside.cy'
import './run-0/heltFrisk.cy'
import './run-1/inntektsmelding.cy'
import './run-1/narmesteleder.cy'
import './run-2/oppfolgingsplanOppgaver.cy'
import './run-3/snartSluttOppgave.cy'
