export const TidslinjeUtdragTekster = {
    // teksterMedArbeidsgiver
    'tidslinje.utdrag.sykmeldt-hva-naa.med-arbeidsgiver.ingress': '<p>Du bestemmer selv om du vil bruke sykmeldingen eller avbryte den. Du kan også jobbe i kombinasjon med sykmelding. Det kommer an på hva sykdommen din tillater og hva det er praktisk mulig å få til på arbeidsplassen.</p>',
    'tidslinje.utdrag.sykmeldt-hva-naa.med-arbeidsgiver.mer': '<p>Greit å vite: Arbeidsgiveren har plikt til å legge til rette for at du kan jobbe helt eller delvis selv om du er syk.</p><p>Husk at du alltid kan vurdere <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmelding-ulike-former/gradertsykemelding">gradert sykmelding</a>.</p><p>Vet du at fraværet blir kort, kan det være like greit med <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmelding-ulike-former/egenmelding">egenmelding</a>, så slipper du å gå til legen.</p><p>Les mer om <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmeldt">sykmelding og sykepenger</a> eller se filmen <a href="https://video.qbrick.com/play2/embed/player?accountId=763558&mediaId=B248D6CB&configId=default&pageStyling=adaptive&autoplay=false&repeat=false&sharing=false&download=true">Hva skjer etter at jeg har sendt sykmeldingen?</a></p>',
    'tidslinje.utdrag.sykmeldt-hva-naa.med-arbeidsgiver.tittel': 'Når du er blitt syk',

    'tidslinje.utdrag.snakk-med-arbeidsgiver.ingress': '<p>Du har vært sykmeldt en stund, og nå er det tid for at du og lederen din fyller ut oppfølgingsplanen sammen – med mindre det er åpenbare grunner til å la være.</p>',
    'tidslinje.utdrag.snakk-med-arbeidsgiver.mer': '<p>Oppfølgingsplanen skal gjøre det lettere å tenke gjennom:</p><ul><li>Er det noen arbeidsoppgaver jeg kan gjøre selv om jeg er syk?</li><li>Er det noe som kan gjøres for at jeg kan få det til?</li></ul><p>Les mer om <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmeldt/hva-er-en-oppfolgingsplan">oppfølgingsplanen</a> eller se filmen <a href="http://video.qbrick.com/play2/embed/player?accountId=763558&mediaId=25edfd35-00015227-b68553ad&configId=default&pageStyling=adaptive&autoplay=true&repeat=true&sharing=true">om den digitale oppfølgingsplanen</a>.</p><p>Husk at du alltid kan vurdere <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmelding-ulike-former/gradertsykemelding">gradert sykmelding</a>.</p>',
    'tidslinje.utdrag.snakk-med-arbeidsgiver.tittel': 'Hvordan går det?',

    'tidslinje.utdrag.dialogmote-arbeidsgiver.ingress': '<p>Nå er tiden kommet for å diskutere situasjonen nærmere med lederen din. Hvilke muligheter ser dere framover?</p>',
    'tidslinje.utdrag.dialogmote-arbeidsgiver.mer': '<p>Arbeidsgiveren har ansvar for at dere møtes til en samtale før det har gått 7 uker. Unntaket er naturligvis hvis du er alvorlig syk eller du er i en annen situasjon som gjør det vanskelig.</p><p>Les mer om <a href="https://www.nav.no/no/bedrift/oppfolging/sykmeldt-arbeidstaker/relatert-informasjon/slik-folger-du-opp-sykmeldte/dialogmote-1-arbeidsgiver_kap">dialogmøte på arbeidsplassen</a></p>',
    'tidslinje.utdrag.dialogmote-arbeidsgiver.tittel': 'Tid for dialogmøte med lederen din',

    'tidslinje.utdrag.aktivitetskrav-med-arbeidsgiver.ingress': '<p>Du har plikt til å være i aktivitet mens du er sykmeldt – hvis det er mulig. Hensikten er å unngå at sykefraværet blir unødvendig langt. Ved alvorlig sykdom er det naturligvis unntak.</p>',
    'tidslinje.utdrag.aktivitetskrav-med-arbeidsgiver.mer': '<p>Når du har vært sykmeldt i åtte uker, er det NAVs oppgave å vurdere om du oppfyller aktivitetsplikten, eller om sykepengene dine skal stanses.</p><p>Når vi vurderer om du oppfyller aktivitetsplikten, ser vi på hva arbeidsgiveren din har gjort for at du kan jobbe. Vi vurderer også om du er for syk til å være i aktivitet.</p><p>Er du allerede delvis tilbake i arbeid, oppfyller du aktivitetsplikten og kan fortsatt få sykepenger.</p><p>Les mer om <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykepenger/hva-er-aktivitetsplikten">aktivitetsplikten</a> eller se filmen <a href="https://video.qbrick.com/play2/embed/player?accountId=763558&mediaId=7731f50f-00015227-3808f149&configId=default&pageStyling=adaptive&autoplay=false&repeat=true&sharing=true&download=true">Hva innebærer aktivitetsplikten?</a></p>',
    'tidslinje.utdrag.aktivitetskrav-med-arbeidsgiver.tittel': 'Oppfyller du aktivitetsplikten?',

    'tidslinje.utdrag.dialogmote-nav.med-arbeidsgiver.ingress': '<p>Det kan hende du snart blir innkalt til dialogmøte med NAV – hvis du ikke allerede har vært der? I dette møtet kommer du sammen med arbeidsgiveren, av og til blir også den som har sykmeldt deg invitert.</p>',
    'tidslinje.utdrag.dialogmote-nav.med-arbeidsgiver.mer': '<p>Meningen er å komme fram til noe som kan hjelpe deg videre. Veilederen fra NAV leder møtet og er en nøytral deltaker som stiller spørsmål til alle som er til stede.</p><p>Du forteller om jobben og situasjonen din: hva som går bra og hva som er vanskelig. Arbeidsgiveren din forteller om arbeidsplassen, hva som er forsøkt og hvilke muligheter som finnes.</p><p>Vi ser på oppfølgingsplanen som du og arbeidsgiveren allerede har laget sammen. Ser vi noen flere muligheter på arbeidsplassen? Trenger du noen helsetjenester, eller er det noe NAV kan bidra med?</p><p>Til slutt oppsummerer NAV-veilederen møtet og avklarer hvem som skal gjøre hva og når det skal skje.</p><p>Les mer om <a href="https://www.nav.no/no/bedrift/oppfolging/sykmeldt-arbeidstaker/relatert-informasjon/slik-folger-du-opp-sykmeldte/dialogmote-2-og-3-nav_kap">dialogmøte i regi av NAV</a> eller se filmen <a href="http://video.qbrick.com/play2/embed/player?accountId=763558&mediaId=0915c6b6-00015227-23a22cb3&configId=default&pageStyling=adaptive&autoplay=true&repeat=true&sharing=true">Hva skjer i dialogmøtet som NAV innkaller til?</a></p>',
    'tidslinje.utdrag.dialogmote-nav.med-arbeidsgiver.tittel': 'Tid for dialogmøte med NAV',

    'tidslinje.utdrag.langtidssykmeldt-med-arbeidsgiver.ingress': '<p>Du har kanskje vært i dialogmøte med NAV? Da handler det om å følge opp det som ble avtalt i møtet. Planene avhenger av hva som er mulig ut fra helsesituasjonen din.</p>',
    'tidslinje.utdrag.langtidssykmeldt-med-arbeidsgiver.mer': '<p>Arbeidsgiveren din har fortsatt et ansvar. Du kan be NAV om et <a href="https://www.nav.no/no/bedrift/oppfolging/sykmeldt-arbeidstaker/relatert-informasjon/slik-folger-du-opp-sykmeldte/dialogmote-2-og-3-nav_kap">nytt dialogmøte</a> sammen med lederen din og eventuelt legen.</p>',
    'tidslinje.utdrag.langtidssykmeldt-med-arbeidsgiver.tittel': 'Når du har vært sykmeldt lenge',

    'tidslinje.utdrag.sluttfasen.med-arbeidsgiver-2.ingress': '<p>Det nærmer seg datoen da du ikke lenger kan få sykepenger. Sammen med arbeidsgiveren din eller en NAV-veileder kan du planlegge veien videre. <a href="%ARBEIDSRETTETOPPFOLGING%" target="_blank">Se hva du kan gjøre.</a></p>',
    'tidslinje.utdrag.sluttfasen.med-arbeidsgiver-2.mer': '<p>Blir du sykmeldt lenger enn 52 uker til sammen, har du ikke lenger rett til sykepenger. Du har ulike alternativer for å unngå å stå uten inntekt når sykepengene tar slutt. Se mer om hvordan du kan planlegge veien videre sammen med arbeidsgiveren din eller en NAV-veileder. <a href="%ARBEIDSRETTETOPPFOLGING%" target="_blank">Gå til alternativene.</a></p>',
    'tidslinje.utdrag.sluttfasen.med-arbeidsgiver-2.tittel': 'Snart slutt på sykepengene',

    // teksterUtenArbeidsgiver
    'tidslinje.utdrag.sykmeldt-hva-naa.uten-arbeidsgiver.ingress': '<p>Du bestemmer selv om du vil bruke sykmeldingen. Du kan enten bekrefte den eller avbryte den.</p>',
    'tidslinje.utdrag.sykmeldt-hva-naa.uten-arbeidsgiver.mer': '<p>I noen tilfeller kan det være godt å få jobbe selv om du er syk. Det kommer an på hva sykdommen din tillater og hva som er praktisk mulig å få til.</p><p>Ta gjerne kontakt med NAV-kontoret hvis du vil drøfte hvilke muligheter du har.</p><p>Husk at du alltid kan vurdere <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmelding-ulike-former/gradertsykemelding">gradert sykmelding</a>.</p><p><a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykmeldt">Les mer om sykmelding og sykepenger</a></p>',
    'tidslinje.utdrag.sykmeldt-hva-naa.uten-arbeidsgiver.tittel': 'Når du er blitt syk',

    'tidslinje.utdrag.mulighet-for-aktivitet-uten-arbeidsgiver.ingress': '<p>Du har vært sykmeldt en stund, og avhengig av helsesituasjonen er det tid for å vurdere veien videre:</p><ul><li>Er det noen arbeidsoppgaver jeg kan gjøre selv om jeg er syk?</li><li>Er det noe jeg trenger for å kunne komme tilbake i jobb?</li></ul>',
    'tidslinje.utdrag.mulighet-for-aktivitet-uten-arbeidsgiver.mer': '<p>Ta gjerne kontakt med NAV-kontoret hvis du vil drøfte hvilke muligheter du har.</p><p>Etter åtte uker skal NAV vurdere om du fortsatt har rett til sykepenger. Reglene sier at du har plikt til å være i aktivitet hvis det er mulig. Hensikten er å unngå at sykefraværet blir unødvendig langt. Ved alvorlig sykdom er det naturligvis unntak.</p><p>Les mer om <a href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/sykepenger/hva-er-aktivitetsplikten">aktivitetsplikten</a> eller se filmen <a href="https://video.qbrick.com/play2/embed/player?accountId=763558&mediaId=7731f50f-00015227-3808f149&configId=default&pageStyling=adaptive&autoplay=false&repeat=true&sharing=true&download=true">Hva innebærer aktivitetsplikten?</a></p>',
    'tidslinje.utdrag.mulighet-for-aktivitet-uten-arbeidsgiver.tittel': 'Hvordan går det?',

    'tidslinje.utdrag.snakk-med-nav.ingress': '<p>NAV skal hjelpe deg med å vurdere mulighetene dine og vil eventuelt innkalle deg til samtale. Meningen er å komme fram til noe som kan hjelpe deg videre.</p>',
    'tidslinje.utdrag.snakk-med-nav.mer': '<p>Husk at du kan registrere CV-en din på nav.no, hvor du også finner alle offentlig utlyste stillinger. Opplysningene du legger inn kan brukes i dialogen med NAV.</p><p>På nav.no kan du lage din egen aktivitetsplan. Legg inn aktiviteter som du mener er nyttige for å komme i jobb. Du kan starte en dialog med veilederen når du er inne i planen. Veilederen kan også starte en dialog med deg.</p><p>Les mer om <a href="https://www.nav.no/no/person/arbeid/oppfolging-og-tiltak-for-a-komme-i-jobb/relatert-informasjon/din-aktivitetsplan">aktivitetsplanen</a>.</p>',
    'tidslinje.utdrag.snakk-med-nav.tittel': 'Har du snakket med en veileder på NAV-kontoret?',

    'tidslinje.utdrag.aktivitetsplan-uten-arbeidsgiver.ingress': '<p>Hvis du ikke allerede har vært på NAV-kontoret og laget en aktivitetsplan, kan du logge deg inn på nav.no og ta i bruk den digitale aktivitetsplanen.</p>',
    'tidslinje.utdrag.aktivitetsplan-uten-arbeidsgiver.mer': '<p>Legg inn aktiviteter som du mener er nyttige for å komme i jobb. Du kan starte en dialog med veilederen når du er inne i planen. Veilederen kan også starte en dialog med deg.</p><p>Planen vil avhenge av hvilken aktivitet som er mulig ut fra helsesituasjonen din.</p><p>Les mer om <a href="https://www.nav.no/no/person/arbeid/oppfolging-og-tiltak-for-a-komme-i-jobb/relatert-informasjon/din-aktivitetsplan">aktivitetsplanen</a>.</p>',
    'tidslinje.utdrag.aktivitetsplan-uten-arbeidsgiver.tittel': 'Har du og veilederen laget en plan?',

    'tidslinje.utdrag.sluttfasen.uten-arbeidsgiver-2.ingress': '<p>Det nærmer seg datoen da du ikke lenger kan få sykepenger. Sammen med en NAV-veileder kan du planlegge veien videre. <a href="%ARBEIDSRETTETOPPFOLGING%" target="_blank">Se hva du kan gjøre.</a></p>',
    'tidslinje.utdrag.sluttfasen.uten-arbeidsgiver-2.mer': '<p>Blir du sykmeldt lenger enn 52 uker til sammen, har du ikke lenger rett til sykepenger. Du har ulike alternativer for å unngå å stå uten inntekt når sykepengene tar slutt. Se mer om hvordan du kan planlegge veien videre sammen med en NAV-veileder. <a href="%ARBEIDSRETTETOPPFOLGING%" target="_blank">Gå til alternativene.</a></p>',
    'tidslinje.utdrag.sluttfasen.uten-arbeidsgiver-2.tittel': 'Snart slutt på sykepengene',

    // Friskmelding
    'friskmelding.bjorn': 'Hei, et lite tips: Har det blitt lettere for deg å komme tilbake til jobb, kan du avbryte sykmeldingen før den er helt over.',
    'friskmelding.bjorn-knapp': 'Jeg vil vite mer',
    'friskmelding.info-tittel.delvis': 'Kan du jobbe mer enn det sykmeldingen sier?',
    'friskmelding.info-tittel.helt': 'Trenger du ikke være sykmeldt lenger og vil tilbake til jobb?',
    'friskmelding.info.delvis': '<ul><li>Ta kontakt med arbeidsgiveren din.</li><li>Du trenger ikke ny sykmelding fra legen.</li><li>Når du får søknaden om sykepenger til utfylling, skriver du inn hvor mye du har jobbet.</li></ul>',
    'friskmelding.info.helt': '<ul><li>Ta kontakt med arbeidsgiveren din.</li><li>Du trenger ikke si fra til legen eller spørre NAV.</li><li>Når du får søknaden om sykepenger til utfylling, skriver du inn datoen du begynte å jobbe igjen.</li></ul>',
}
