export const AktivitetskravTekster = {
    'aktivitetskrav-varsel.info': 'Under korona-pandemien følger vi smittevernrådene fra myndighetene. Derfor vil vi ikke kreve aktiviteter av deg som kommer i konflikt med smittevernet.',
    'aktivitetskrav-varsel.kvittering': 'Du har bekreftet at du har lest om aktivitetsplikten %DATO%.',
    'aktivitetskrav-varsel.tittel': 'Påminnelse om aktivitet',
    'aktivitetskrav-varsel.ingress': 'Du har snart vært sykmeldt i åtte uker. NAV skal vurdere om du oppfyller aktivitetsplikten og om du fortsatt har rett til sykepenger.',
    'aktivitetskrav-varsel.innhold.MED_ARBEIDSGIVER': '<p>Er du allerede tilbake i jobb helt eller delvis? Da bruker du søknaden om sykepenger til å oppgi når du startet og hvor mye du jobber. Slik vet vi at du allerede oppfyller aktivitetsplikten.</p><h2 class="typo-undertittel">Aktivitetsplikt</h2><p>Som sykmeldt har du en plikt til å være i aktivitet hvis det er mulig. Hensikten er å unngå at sykefraværet ditt blir unødvendig langt. Aktivitet vil si å jobbe noe i kombinasjon med å være sykmeldt. Et eksempel er å jobbe 50 prosent og være 50 prosent sykmeldt. Er det noen arbeidsoppgaver du kan delta i selv om du er syk?</p><h2 class="typo-undertittel">Hva må du gjøre nå?</h2><p>Det er viktig at du har god dialog med arbeidsgiveren din om hva som skal til for at du kan være noe i arbeid. Hvis dere ikke har hatt dialog, ta kontakt og be om en samtale.</p><h2 class="typo-undertittel">Hva skjer hvis aktivitet ikke er mulig?</h2><p>Hvis det ikke er mulig å legge til rette for at du kan jobbe noe, må arbeidsgiveren din gi skriftlig beskjed til NAV. Hvis du er for syk til å være i aktivitet, må den som har sykmeldt deg begrunne dette i sykmeldingen.</p><h2 class="typo-undertittel">NAV vurderer aktivitetsplikten</h2><p>NAV har som oppgave å vurdere aktivitetsplikten basert på opplysninger fra arbeidsgiveren din og fra den som har sykmeldt deg. Utfallet av vurderingen kan være:<ol type="A"><li>Aktivitetsplikten er oppfylt fordi du er delvis tilbake i arbeid. Utbetalingen av sykepenger fortsetter.</li><li>Du får unntak fra aktivitetsplikten på grunn av helsesituasjonen, eller fordi det ikke er mulig å tilrettelegge på arbeidsplassen. Utbetalingen av sykepenger fortsetter.</li><li>Aktivitetsplikten er ikke oppfylt. Du kan miste retten til sykepenger, og utbetalingen stanses.</li></ol>',
    'aktivitetskrav-varsel.innhold.UTEN_ARBEIDSGIVER': '<p>Er du allerede tilbake i jobb helt eller delvis? Da bruker du søknaden om sykepenger til å oppgi når du startet og hvor mye du jobber. Slik vet vi at du allerede oppfyller aktivitetsplikten.</p><h2 class="typo-undertittel">Aktivitetsplikt</h2><p>Som sykmeldt har du en plikt til å være i aktivitet hvis det er mulig. Hensikten er å unngå at sykefraværet ditt blir unødvendig langt. Aktivitet vil si å jobbe noe i kombinasjon med å være sykmeldt. Et eksempel er å jobbe 50 prosent og være 50 prosent sykmeldt.</p>\n<p>Er du selvstendig næringsdrivende eller frilanser, er det kanskje noen av arbeidsoppgavene dine du fortsatt kan utføre?\nEr du arbeidsledig og sykmeldt, er det viktig å planlegge hvilke aktiviteter eller tiltak du har behov for slik at du kan komme i jobb igjen.</p>\n<p>Du kan selv ta kontakt med NAV-kontoret der du bor hvis du ikke har fått innkalling og ønsker en samtale med en veileder. Husk at du kan registrere din CV på nav.no. Her får du også tilgang til alle offentlig utlyste stillinger. Opplysningene du legger inn, kan brukes i dialogen med NAV.</p>\n<p>Hvis du er for syk til å være i aktivitet, må den som har sykmeldt deg begrunne dette i sykmeldingen. Ved alvorlig sykdom er det unntak fra aktivitetsplikten.</p><h2 class="typo-undertittel">NAV vurderer aktivitetsplikten</h2><p>NAV har som oppgave å vurdere aktivitetsplikten basert på opplysninger fra den som har sykmeldt deg. Utfallet av vurderingen kan være:</p><ol type="A"><li>Aktivitetsplikten er oppfylt fordi du er delvis tilbake i arbeid. Utbetalingen av sykepenger fortsetter.</li><li>Du får unntak fra aktivitetsplikten på grunn av helsesituasjonen. Utbetalingen av sykepenger fortsetter.</li><li>Aktivitetsplikten er ikke oppfylt. Du kan miste retten til sykepenger, og utbetalingen stanses.</li></ol>',
    'aktivitetskrav-varsel.alt.MED_ARBEIDSGIVER': 'Sykmeldt og arbeidsgiver',
    'aktivitetskrav-varsel.alt.UTEN_ARBEIDSGIVER': 'Sykmeldt og NAV-veileder',
}
